server:
  port: 8080
  servlet:
    context-path: /community
spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///community?serverTimezon=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 6
      max-active: 15
      min-idle: 5
      connect-timeout: 30000
  mail:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    host: smtp.aliyun.com
    port: 465
    username: lutong99@aliyun.com
    protocol: smtp
  config:
    import: secret.config.yaml
  redis:
    port: 6379
    database: 11
  kafka:
    bootstrap-servers: 172.16.15.7:9092
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      group-id: community-consumer-group
  elasticsearch:
    uris: http://172.16.15.7:9200
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
    scheduling:
      pool:
        size: 10
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.scheduler.instanceId: AUTO
      # springboot>2.5.6后使用这个 org.springframework.scheduling.quartz.LocalDataSourceJobStore，以前使用的 org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 5
    scheduler-name: communityNowcoderScheduler
    jdbc:
      initialize-schema: never

mybatis:
  type-aliases-package: org.example.newcoder.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#logging:
#  level:
#    org.example.nowcoder: debug

pagehelper:
  reasonable: true

community:
  path:
    domain: http://localhost:8080
    upload: C:/usr/local/upload
    wk:
      image-path: C:/usr/local/upload/wk
      command: C:/Program Files/wkhtmltopdf/bin/wkhtmltoimage
  sensitive:
    file:
      path: sensitive/words.copy.txt
  kaptcha:
    image:
      width: 100
      height: 40
    textproducer:
      font:
        size: 32
        color: black
      char:
        string: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
        length: 4
    noise:
      impl: com.google.code.kaptcha.impl.NoNoise
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    endpoint-without: oss-cn-beijing.aliyuncs.com
    bucket-name: community-nowcoder
    header-prefix: header/
    share-prefix: share/images/


