server:
  port: 8080
  servlet:
    context-path: /community
spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///community?serverTimezon=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 6
      max-active: 15
      min-idle: 5
      connect-timeout: 30000
  mail:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    host: smtp.aliyun.com
    port: 465
    username: lutong99@aliyun.com
    protocol: smtp
  config:
    import: secret.config.yaml

mybatis:
  type-aliases-package: org.example.newcoder.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

#logging:
#  level:
#    org.example.nowcoder: debug

pagehelper:
  reasonable: true

community:
  path:
    domain: http://localhost:8080
    upload: C:/usr/local/upload
  sensitive:
    file:
      path: sensitive/words.copy.txt
  kaptcha:
    image:
      width: 100
      height: 40
    textproducer:
      font:
        size: 32
        color: black
      char:
        string: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ
        length: 4
    noise:
      impl: com.google.code.kaptcha.impl.NoNoise
