package org.example.nowcoder.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.example.nowcoder.entity.DiscussPost;
import org.example.nowcoder.entity.DiscussPostExample;
@Mapper
public interface DiscussPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int countByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int deleteByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int insert(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int insertSelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    List<DiscussPost> selectByExampleWithBLOBs(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    List<DiscussPost> selectByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    DiscussPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int updateByExampleSelective(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int updateByExample(@Param("record") DiscussPost record, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int updateByPrimaryKeySelective(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(DiscussPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbggenerated Fri Aug 11 13:17:41 CST 2023
     */
    int updateByPrimaryKey(DiscussPost record);
}